resolver: lts-23.25 # Snapshot mais moderno e estável

packages:
  - .

build:
  haddock: false

extra-deps:
  - happy-1.20.0
  - mtl-2.2.2
  - transformers-0.5.6.2
# Configurações opcionais para resolver conflitos se necessário
# allow-newer: true
# allow-newer-deps:
#   - mtl
#   - transformers
